import { Router } from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { z } from "zod";
import { config } from "../config";
import { authenticate } from "../middleware/auth";
import { validate } from "../middleware/validation";
import { audit } from "../services/audit";
import { insert, readDb, update } from "../utils/json-db";
import { fail, ok } from "../utils/api";
import type { User } from "../types";
const router = Router();
const credentials = z.object({ email: z.string().email().transform(v => v.toLowerCase()), password: z.string().min(8) });
const safeUser = (u: User) => ({ id: u.id, email: u.email, fullName: u.fullName, mobile: u.mobile, role: u.role, status: u.status });
const tokens = (u: User) => ({ accessToken: jwt.sign({ sub: u.id, role: u.role }, config.jwtSecret, { expiresIn: "15m" }), refreshToken: jwt.sign({ sub: u.id }, config.refreshSecret, { expiresIn: "30d" }) });
router.post("/register", validate(credentials.extend({ fullName: z.string().min(2), mobile: z.string().min(7) })), async (req, res) => { const users = await readDb<User>("users"); if (users.some(u => u.email === req.body.email)) return fail(res, "Email already registered", 409); const user = await insert<User>("users", { ...req.body, passwordHash: await bcrypt.hash(req.body.password, 12), role: "Normal User", status: "active", failedLoginAttempts: 0, loginHistory: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await audit("user.register", user.id); return ok(res, { user: safeUser(user), ...tokens(user) }, "Account created", 201); });
router.post("/login", validate(credentials), async (req, res) => { const users = await readDb<User>("users"); const user = users.find(u => u.email === req.body.email); if (!user || user.lockUntil && new Date(user.lockUntil) > new Date() || !(user && await bcrypt.compare(req.body.password, user.passwordHash))) { if (user) await update<User>("users", user.id, { failedLoginAttempts: user.failedLoginAttempts + 1, lockUntil: user.failedLoginAttempts >= 4 ? new Date(Date.now() + 15 * 60_000).toISOString() : undefined }); await audit("auth.login.failed", user?.id); return fail(res, "Invalid email or password", 401); } await update<User>("users", user.id, { failedLoginAttempts: 0, lockUntil: undefined, loginHistory: [...user.loginHistory, new Date().toISOString()].slice(-20) }); await audit("auth.login", user.id); return ok(res, { user: safeUser(user), ...tokens(user) }, "Signed in"); });
router.get("/me", authenticate, (req, res) => ok(res, safeUser(req.auth!.user)));
router.post("/refresh", (req, res) => { try { const payload = jwt.verify(req.body.refreshToken, config.refreshSecret) as { sub: string }; return ok(res, { accessToken: jwt.sign({ sub: payload.sub }, config.jwtSecret, { expiresIn: "15m" }) }); } catch { return fail(res, "Invalid refresh token", 401); } });
router.post("/logout-all", authenticate, async (req, res) => { await audit("auth.logout_all", req.auth!.user.id); return ok(res, null, "Signed out from all devices"); });
router.post("/forgot-password", validate(z.object({ email: z.string().email().transform(v => v.toLowerCase()) })), async (req, res) => { const user = (await readDb<User>("users")).find(item => item.email === req.body.email); if (user) await audit("auth.password_reset_requested", user.id); const resetToken = user ? jwt.sign({ sub: user.id, purpose: "password-reset" }, config.jwtSecret, { expiresIn: "15m" }) : undefined; return ok(res, { resetToken }, "If the account exists, reset instructions were created"); });
router.post("/reset-password", validate(z.object({ token: z.string().min(1), password: z.string().min(8) })), async (req, res) => { try { const payload = jwt.verify(req.body.token, config.jwtSecret) as { sub: string; purpose: string }; if (payload.purpose !== "password-reset") return fail(res, "Invalid reset token", 400); await update<User>("users", payload.sub, { passwordHash: await bcrypt.hash(req.body.password, 12), updatedAt: new Date().toISOString() }); await audit("auth.password_reset", payload.sub); return ok(res, null, "Password reset successfully"); } catch { return fail(res, "Invalid or expired reset token", 400); } });
router.post("/change-password", authenticate, validate(z.object({ currentPassword: z.string().min(8), password: z.string().min(8) })), async (req, res) => { if (!(await bcrypt.compare(req.body.currentPassword, req.auth!.user.passwordHash))) return fail(res, "Current password is incorrect", 400); await update<User>("users", req.auth!.user.id, { passwordHash: await bcrypt.hash(req.body.password, 12), updatedAt: new Date().toISOString() }); await audit("auth.password_changed", req.auth!.user.id); return ok(res, null, "Password changed successfully"); });
export default router;
