import { Router } from "express";
import { z } from "zod";
import { authenticate } from "../middleware/auth";
import { validate } from "../middleware/validation";
import { audit } from "../services/audit";
import { insert, paginate, readDb, remove, update } from "../utils/json-db";
import { fail, ok } from "../utils/api";
const bodySchema = z.object({ title: z.string().min(1).max(120), amount: z.coerce.number().nonnegative(), category: z.string().optional(), date: z.string().optional(), description: z.string().max(500).optional() });
const router = Router(); router.use(authenticate);
export function resourceRoutes(name: string) { const r = Router(); r.use(authenticate); r.get("/", async (req, res) => { const records = (await readDb<Record<string, unknown>>(name)).filter(item => item.userId === req.auth!.user.id || req.auth!.permissions.includes("*")); const result = paginate(records, Number(String(req.query.page ?? 1)), Number(String(req.query.limit ?? 20))); return res.json({ success: true, message: "Records loaded", ...result }); }); r.post("/", validate(bodySchema), async (req, res) => { const record = await insert(name, { ...req.body, userId: req.auth!.user.id, date: req.body.date ?? new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await audit(`${name}.create`, req.auth!.user.id, { recordId: record.id }); return ok(res, record, "Record created", 201); }); r.patch("/:id", validate(bodySchema.partial()), async (req, res) => { const existing = (await readDb<Record<string, unknown>>(name)).find(item => item.id === String(req.params.id) && (item.userId === req.auth!.user.id || req.auth!.permissions.includes("*"))); if (!existing) return fail(res, "Record not found", 404); const record = await update(name, String(req.params.id), { ...req.body, updatedAt: new Date().toISOString() }); await audit(`${name}.update`, req.auth!.user.id, { recordId: String(req.params.id) }); return ok(res, record, "Record updated"); }); r.delete("/:id", async (req, res) => { const existing = (await readDb<Record<string, unknown>>(name)).find(item => item.id === String(req.params.id) && (item.userId === req.auth!.user.id || req.auth!.permissions.includes("*"))); if (!existing) return fail(res, "Record not found", 404); await remove(name, String(req.params.id)); await audit(`${name}.delete`, req.auth!.user.id, { recordId: String(req.params.id) }); return ok(res, null, "Record deleted"); }); return r; }
export default router;
